# Site settings
title: NoPad
description: Erblocker的NoPad计划
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: NoPad
user_description: 我们旨在改善云课堂教学模式，所以这里提供了一些关于修复破解少年派/睿易派的解决方案。
user_title: 展望星空  拥抱未来
email: chainsx.outlook.com
github_username:  chainsx

# Google-analytics
google-analytics:
  id: "pzhrhlx@gmail.com"

exclude: ['package.json', 'src' , 'node_modules']
